# Generated by Django 5.2 on 2025-04-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العيادة')),
                ('days_available', models.JSONField(blank=True, default=list, verbose_name='أيام العمل')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطبيب')),
                ('specialty', models.CharField(max_length=100, verbose_name='التخصص')),
                ('max_sessions', models.IntegerField(default=10, verbose_name='الحد الأقصى للجلسات')),
                ('preferred_clinics', models.JSONField(blank=True, default=list, verbose_name='تفضيلات العيادات')),
                ('preferred_days', models.JSONField(blank=True, default=list, verbose_name='تفضيلات الأيام')),
                ('unavailable_days', models.JSONField(blank=True, default=list, verbose_name='الأيام غير المتاحة')),
                ('shift_preference', models.JSONField(blank=True, default=list, verbose_name='تفضيلات المناوبة')),
                ('has_training', models.BooleanField(default=False, verbose_name='مدرب')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_present', models.BooleanField(default=True, verbose_name='حاضر')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_app.doctor', verbose_name='الطبيب')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('الأحد', 'الأحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس')], max_length=20, verbose_name='اليوم')),
                ('session', models.IntegerField(choices=[(1, 'الصباحية'), (2, 'المسائية')], verbose_name='الفترة')),
                ('is_special', models.BooleanField(default=False, verbose_name='عيادة خاصة')),
                ('is_coverage', models.BooleanField(default=False, verbose_name='تغطية')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_app.clinic', verbose_name='العيادة')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors_app.doctor', verbose_name='الطبيب')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء الإجازة')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الإجازة')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_app.doctor', verbose_name='الطبيب')),
            ],
        ),
    ]
