# Generated by Django 5.2 on 2025-04-17 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('session_1_enabled', models.BooleanField(default=True, verbose_name='جلسة صباحية')),
                ('session_2_enabled', models.BooleanField(default=True, verbose_name='جلسة مسائية')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors_app.clinic', verbose_name='العيادة')),
            ],
        ),
    ]
