# Generated by Django 4.2.15 on 2025-04-18 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0002_locationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='week_start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='بداية الأسبوع'),
        ),
    ]
