# Generated by Django 5.2 on 2025-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0003_scheduleentry_week_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationconfig',
            name='session_1_enabled',
        ),
        migrations.RemoveField(
            model_name='locationconfig',
            name='session_2_enabled',
        ),
        migrations.AddField(
            model_name='locationconfig',
            name='period_1_enabled',
            field=models.BooleanField(default=True, verbose_name='صباحي - الأولى'),
        ),
        migrations.AddField(
            model_name='locationconfig',
            name='period_2_enabled',
            field=models.BooleanField(default=True, verbose_name='صباحي - الثانية'),
        ),
        migrations.AddField(
            model_name='locationconfig',
            name='period_3_enabled',
            field=models.BooleanField(default=True, verbose_name='مسائي - الأولى'),
        ),
        migrations.AddField(
            model_name='locationconfig',
            name='period_4_enabled',
            field=models.BooleanField(default=True, verbose_name='مسائي - الثانية'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='session',
            field=models.IntegerField(choices=[(1, 'صباحي - الأولى'), (2, 'صباحي - الثانية'), (3, 'مسائي - الأولى'), (4, 'مسائي - الثانية')], verbose_name='الفترة'),
        ),
    ]
