# Generated by Django 5.2 on 2025-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0004_remove_locationconfig_session_1_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='has_conflict',
            field=models.BooleanField(default=False, verbose_name='تعارض في الجدول'),
        ),
    ]
