# Generated by Django 5.2 on 2025-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0007_doctor_day_shift_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='day_shift_preferences',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='preferred_days',
            field=models.JSONField(blank=True, default=dict, verbose_name='تفضيلات اليوم مع الشيفت'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='shift_preference',
            field=models.JSONField(blank=True, default=list, verbose_name='تفضيلات المناوبة'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='unavailable_days',
            field=models.JSONField(blank=True, default=dict, verbose_name='الايام غير المتاحه مع الشيفت'),
        ),
    ]
