# Generated by Django 5.2 on 2025-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0008_remove_doctor_day_shift_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='تم تعديله يدويًا'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list, verbose_name='تفضيلات الأيام مع الشيفت'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='unavailable_days',
            field=models.JSONField(blank=True, default=list, verbose_name='الأيام غير المتاحة مع الشيفت'),
        ),
    ]
